---
- name: Build and push Docker image
  hosts: localhost
  gather_facts: False
  become: true

  tasks:
    - name: Build the Docker image
      docker_image:
        name: dignity26/my_tomcat_image:latest1
        source: build
        build:
          path: .  # Replace with the directory containing your Dockerfile
          pull: yes
        state: present
        force_tag: yes

    - name: Log in to Docker Hub
      docker_login:
        username: dignity26
        password: Ajit$1994  # It's recommended to use Ansible vault to store sensitive information like passwords.

    - name: Push the Docker image to Docker Hub
      docker_image:
        name: dignity26/my_tomcat_image:latest1
        source: local
        push: yes