---
- name: Build and push Docker image
  hosts: localhost
  gather_facts: False
  become: true

  vars:
    dockerhub_username: "dignity26"
    dockerhub_password: "Ajit$1994"  # It's recommended to use Ansible vault to store sensitive information like passwords.
    image_name: "dignity26/my_tomcat_image"  # Replace with your desired image name
    image_tag: "latest"  # Replace with your desired image tag

  tasks:
    - name: Build the Docker image
      community.general.docker_compose:
        build:
          context: .
        pull: yes
        force: yes

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Tag the Docker image with the desired name and tag
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build

    - name: Push the Docker image to Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
