---
- name: Build and push Docker image
  hosts: localhost
  become: true

  tasks:
    - name: Build the Docker image
      docker_image:
        name: my_tomcat:latest
        path: .
        build:
          nocache: yes   # Set nocache to true to ignore the cache
        state: present
        force_tag: yes


    - name: adding tag to image
      command: sudo docker tag my_tomcat:latest dignity26/my_tomcat:latest

    - name: Log in to Docker Hub
      docker_login:
        username: dignity26
        password: Ajit$1994  # It's recommended to use Ansible vault to store sensitive information like passwords.

    - name: Push the Docker image to Docker Hub
      docker_image:
        name: dignity26/my_tomcat:latest
        source: local
        push: yes

    - name: removing images from local
      command: sudo docker rmi my_tomcat:latest dignity26/my_tomcat:latest
      ignore_errors: yes