---
- name: Build and push Docker image
  hosts: localhost
  gather_facts: False
  become: true

  vars:
    dockerhub_username: "dignity26"
    dockerhub_password: "Ajit$1994"  # It's recommended to use Ansible vault to store sensitive information like passwords.
    image_name: "my_tomcat_image"    # Replace with your desired image name (without the username)

  tasks:
    - name: Build the Docker image
      docker_image:
        name: "{{ dockerhub_username }}/{{ image_name }}:latest"
        build:
          path: .   # Replace with the directory containing your Dockerfile
          pull: yes

    - name: Log in to Docker Hub
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Push the Docker image to Docker Hub
      docker_image:
        name: "{{ dockerhub_username }}/{{ image_name }}:latest"
        push: yes
