- hosts: all
  become: true

  tasks:
    - name: Remove Docker builder cache
      command: docker builder prune --all --force

    - name: Build the Docker image
      docker_image:
        name: my_tomcat:latest
        build:
          context: .
        source: build
        state: present
        force_tag: yes
          
    - name: adding tag to image
      command: docker tag my_tomcat dignity26/my_tomcat

    - name: Log in to Docker Hub
      docker_login:
        username: dignity26
        password: Ajit$1994  # It's recommended to use Ansible vault to store sensitive information like passwords.

    - name: Push the Docker image to Docker Hub
      command: docker push dignity26/my_tomcat

    - name: removing images from local
      command: docker rmi my_tomcat dignity26/my_tomcat
      ignore_errors: yes