---
- name: Build and push Docker image
  hosts: localhost
  gather_facts: False
  become: true

  tasks:
    - name: Build the Docker image using Docker SDK for Python
      vars:
        dockerfile_directory: .
        image_name: dignity26/my_tomcat_image:latest
      python:
        docker:
          state: build

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: dignity26
        password: Ajit$1994  # It's recommended to use Ansible vault to store sensitive information like passwords.

    - name: Push the Docker image to Docker Hub
      community.docker.docker_image:
        name: dignity26/my_tomcat_image:latest
        push: yes
