---
- name: Build and push Docker image
  hosts: localhost
  gather_facts: False
  become: true

  vars:
    dockerhub_username: "dignity26"
    dockerhub_password: "Ajit$1994"  # It's recommended to use Ansible vault to store sensitive information like passwords.
    image_name: "my_tomcat_image"    # Replace with your desired image name (without the username)

  tasks:
    - name: Build the Docker image
      shell: |
        docker build -t {{ dockerhub_username }}/{{ image_name }}:latest .
      args:
        chdir: .  # Replace with the directory containing your Dockerfile

    - name: Log in to Docker Hub
      shell: |
        docker login -u {{ dockerhub_username }} -p {{ dockerhub_password }}
      environment:
        DOCKER_CLI_ACI: "1"
        DOCKER_CLI_API: "1.41"

    - name: Push the Docker image to Docker Hub
      shell: |
        docker push {{ dockerhub_username }}/{{ image_name }}:latest